name: detria

on: [push]

jobs:
  windows:
    name: Windows Latest MSVC
    runs-on: windows-latest
    strategy:
      fail-fast: true
    steps:
      - name: Setup - CMake
        uses: lukka/get-cmake@latest

      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure
        run: |
          cmake -S . -B build

      - name: Build
        run: |
          cmake --build build --config Debug
          cmake --build build --config Release

      - name: Test
        run: |
          ./bin/detria-test

  linux:
    name: Ubuntu Latest GCC
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - name: Setup - CMake
        uses: lukka/get-cmake@latest

      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure
        run: |
          cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: |
          cmake --build build

      - name: Test
        run: |
          ./bin/detria-test

  osx:
    name: macOS Latest Clang
    runs-on: macos-latest
    strategy:
      fail-fast: true
    steps:
      - name: Setup - CMake
        uses: lukka/get-cmake@latest

      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure
        run: |
          export CC=clang
          export CXX=clang++
          cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: |
          cmake --build build

      - name: Test
        run: |
          ./bin/detria-test

